# https://travis-ci.org/

language: java
jdk: oraclejdk8

env:
    global:
        # Memory limit: 2Go
        - export JAVA_OPTS=-Xmx1g

before_install:
    # VersionEye
    # Disabled: - mvn versioneye:update
    
    # Codecov.io: install
    - pip install --user codecov

# Override: add integration-test Maven phase
script: # Default: `mvn test -B`
    - mvn -B verify
    
    # Site: generate
    # Disabled: - mvn site

# Reporting
after_success:
    # JaCoCo: workaround: Maven `jacoco:report@post-integration-test` goal not working
    - mvn verify -DskipTests -B
    
    # Coveralls.io: publish
    - mvn coveralls:report
    # Codecov.io: publish
    - codecov
